### ISSUE TITLE
Not actually a bug.

### ISSUE THREAD

**Issue by rdebath** [spcutrell/pybrain#1]
But I expect it's not intentional.

Your interpreter uses a cell size of 255 not 256 (or eight bits).

Otherwise, it seems to be working fine, even [mandelbrot](http://esoteric.sange.fi/brainfuck/utils/mandelbrot/) runs, slowly.

**Comment by spcutrell** [comment]
Wow, that was quick.  I appreciate the comment.  

I am actually hoping to post this to reddit at some point to get more criticism.  I am especially interested in what is the "pythonic way" of doing things.  So if you have any other criticism and/or pointers, feel free to lay into the code.

And yeah... it is super slow.  I'd like to do more work optimizing it.  For the short term, I'm just thrilled I got it working.  My C implementation has some major, major holes.

**Comment by rdebath** [comment]
Just bad luck I was looking at the recently modified :smiley: 

Well, for performance the "easy" win is to do run length encoding; that is make any run of each of `+`, `-`, `<`, `>` into a single "instruction" or run around your main loop. You can easily merge `+` with `-` and `>` with `<` too. After that it's probably `[-]` and changing your `[` so that you don't have to do a search every time you skip the loop.

OTOH if you want to make Python faster you might like a look at this [very simple interpreter](https://github.com/alexprengere/PythonBrainFuck) and this [blog post](https://morepypy.blogspot.nl/2011/04/tutorial-part-2-adding-jit.html)  about the techniques to make it run very quick.

As for "Pythonic", I don't know, I always get hung up on the dumb idea of using whitespace for grammar rather than just syntax.
